window.SENTENCES_AUDIO_MAP = {
  "Letter Ll. Sound l. Find the word that starts with Ll.": "assets/audios/sentences/frog_prompt_ll.mp3",
  "Letter Ll. Sound /l/. Find the word that starts with Ll.": "assets/audios/sentences/frog_prompt_ll.mp3",
  "Letter Ll. Find the word that starts with Ll": "assets/audios/sentences/frog_intro_ll.mp3",
  "Letter Nn. Sound n. Find the word that starts with Nn.": "assets/audios/sentences/frog_prompt_nn.mp3",
  "Letter Nn. Sound /n/. Find the word that starts with Nn.": "assets/audios/sentences/frog_prompt_nn.mp3",
  "Letter Nn. Find the word that starts with Nn": "assets/audios/sentences/frog_intro_nn.mp3",
  "Letter Yy. Sound y. Find the word that starts with Yy.": "assets/audios/sentences/frog_prompt_yy.mp3",
  "Letter Yy. Sound /y/. Find the word that starts with Yy.": "assets/audios/sentences/frog_prompt_yy.mp3",
  "Letter Yy. Find the word that starts with Yy": "assets/audios/sentences/frog_intro_yy.mp3",
  "What does Paige like to eat? Paige likes to eat sweet birthday cake.": "assets/audios/sentences/frog_act_3599c61e.mp3",
  "Paige likes to eat sweet birthday cake. What does Paige like to eat?": "assets/audios/sentences/frog_act_3599c61e.mp3",
  "What can Angelo ride? Angelo can ride his brand new red bike.": "assets/audios/sentences/frog_act_b7de28c5.mp3",
  "Angelo can ride his brand new red bike. What can Angelo ride?": "assets/audios/sentences/frog_act_b7de28c5.mp3",
  "What do the children play? Children play a happy game on a sunny day.": "assets/audios/sentences/frog_act_a5033371.mp3",
  "Children play a happy game on a sunny day. What do the children play?": "assets/audios/sentences/frog_act_a5033371.mp3",
  "What is beside the lake? Look at the big wooden gate beside the lake.": "assets/audios/sentences/frog_act_af560e0c.mp3",
  "Look at the big wooden gate beside the lake. What is beside the lake?": "assets/audios/sentences/frog_act_af560e0c.mp3",
  "What can the boat do on the lake? The little sailboat can float on the blue lake.": "assets/audios/sentences/frog_act_41825424.mp3",
  "The little sailboat can float on the blue lake. What can the boat do on the lake?": "assets/audios/sentences/frog_act_41825424.mp3"
};
